language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_dc840765e1d8_key -iv $encrypted_dc840765e1d8_iv
  -in ciduty-twc.json.enc -out ciduty-twc.json -d
- easy_install prettytable
script:
- python3 client.py -w linux -v True
- python3 client.py -w win -v True
- python3 client.py -w osx -u root -v True
