language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_dc840765e1d8_key -iv $encrypted_dc840765e1d8_iv
  -in ciduty-twc.json.enc -out ciduty-twc.json -d
- easy_install prettytable
- easy_install gspread
- easy_install oauth2client
- easy_install pyopenssl
- echo $TRAVIS_COMMIT
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD_NUMBER
- echo $TRAVIS_REPO_SLUG
script:
- pip3 install -r requirements.txt
- python3 client.py -v -ct
